name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install libfmt-dev
      run: sudo apt-get update && sudo apt-get install -y libfmt-dev
    - name: make clean
      run: make clean
    - name: make
      run: make
